package com.osmosyscol.datasuite.persistencia.dao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.osmosyscol.datasuite.logica.dto.FormatoOperacion;

public interface FormatoOperacionDao {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    void insert(FormatoOperacion record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    int updateByPrimaryKey(FormatoOperacion record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    FormatoOperacion selectByPrimaryKey(Long id_formato_operacion) throws SQLException;


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    int deleteByPrimaryKey(Long id_formato_operacion) throws SQLException;

	void eliminarPorFormato(long id_formato);

	List<FormatoOperacion> obtenerOperacionesPorFormato(long id_formato);

	Long obtenerSiguienteId();

	List<Map<String, Object>> obtenerCamposTipoEstructura(Integer id_formato);

	List<FormatoOperacion> obtenerOperacionesPorCarga(Integer id_carga);

	Integer obtenerEstructuraFormatoCarga(Integer id_carga);


}