##############################################################  

database.driver = oracle.jdbc.driver.OracleDriver

database.url = jdbc:oracle:thin:@db.mein.dev3.ssociedades.local:1521:paperles
#database.url = jdbc:oracle:thin:@db.mein.dev2.ssociedades.local:1521:paperles
#database.url = jdbc:oracle:thin:@mein-test.clfil0fpggok.us-east-1.rds.amazonaws.com:1521:paperles
#database.url = jdbc:oracle:thin:@db.smartcash.test.ssociedades.local:1521:paperles
database.user = DEV_DATASUITE 
database.password = DATASUITE
#database.user = TEST_DATASUITE
#database.password = TEST_DATASUITE 

##############################################################

database.name = DATASUITE
database.id = 1
database.defecto = S

##############################################################

database.maxIdle                       = 3
database.maxWait                       = 80000
database.validationQuery               = select '1' from dual
database.testWhileIdle                 = true
database.testOnBorrow                  = true
database.timeBetweenEvictionRunsMillis = 300000

database.initialSize = 1
database.maxActive = 3