##############################################################  

database.driver = oracle.jdbc.driver.OracleDriver
#database.url = jdbc:oracle:thin:@db.smartcash.test.ssociedades.local:1521:paperles
database.url = jdbc:oracle:thin:@db.mein.dev3.ssociedades.local:1521:paperles
#database.url = jdbc:oracle:thin:@db.mein.dev2.ssociedades.local:1521:paperles
database.user = DEV_CREADATOS 
database.password = CREADATOS 

##############################################################

database.name = CREADATOS
database.id = 2
database.defecto = N

##############################################################

database.maxIdle                       = 3
database.maxWait                       = 80000
database.validationQuery               = select '1' from dual
database.testWhileIdle                 = true
database.testOnBorrow                  = true
database.timeBetweenEvictionRunsMillis = 300000

database.initialSize = 1
database.maxActive = 3