################
# --------------------------------------------------------

id			activacion_cuentas

consulta	select nonull(p.nombre) || ' ' || nonull(p.apellido) nombre, p.identificacion, p.correo, c.login,  p.telefono from dst_persona p, dst_credencial c where (upper(c.login) like ('%' || upper(nonull(#id_login#)) || '%') or #id_login# is null ) and c.estado = 'I' and p.id_persona = c.id_persona and (c.id_usuario = #id_usuario# or #id_usuario# is null ) order by c.login
 
nombre_conexion           DATASUITE

# --------------------------------------------------------

resultados:1.titulo			Nombre de Usuario
resultados:1.nombre			login
resultados:1.tipo			string
resultados:1.orden			1
resultados:1.encriptado		S

resultados:2.titulo			Nombre
resultados:2.nombre			nombre
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		S

resultados:3.titulo			Identificación
resultados:3.nombre			identificacion
resultados:3.tipo			string
resultados:3.orden			3
resultados:3.encriptado		S

resultados:4.titulo			Correo electronico
resultados:4.nombre			correo
resultados:4.tipo			string
resultados:4.orden			4
resultados:4.encriptado		S

resultados:4.titulo			Telefono
resultados:4.nombre			telefono
resultados:4.tipo			string
resultados:4.orden			5
resultados:4.encriptado		S

parametros:1.nombre			id_login
parametros:1.tipo			string
parametros:1.encriptado		N
parametros:1.orden			1
parametros:1.filtro			true
parametros:1.titulo			Nombre de usuario

parametros:2.nombre			id_usuario
parametros:2.tipo			integer
parametros:2.encriptado		N
parametros:2.orden			2
parametros:2.filtro			false
parametros:2.titulo			Usuario

#-------------

accionfila.javascript		validarActivacion	

accionfila.parametros:0.nombre	id_login
accionfila.parametros:0.valor	#login#

#-------------
navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do


