color01   #000
color02   #384656
color03   #006600
color04   #006699
color05   #242E3A
color06   #242E3A
color07   #044ebb
color08   #060
color09   #2c68be
color10   #333
color11   #333333
color12   #485814
color13   #666
color14   #999
color15   #a0be24
color16   #a8cc36
color17   #bbb
color18   #c00
color19   #ccc
color20   #daeaab
color21   #ddd
color22   #deecb3
color23   #e6e5e6
color24   #e9d3ad
color25   #ebf1fc
color26   #eeffee
color27   #efefef
color28   #f00
color29   #f0f5ee
color30   #f1f1f1
color31   #f49e06
color32   #f7f7f7
color33   #fcfcfc
color34   #ffeeee
color35   #fff
color36   #fff1f1
color37   #fff6cd
color38   #ffffff
color39   green
color40   red
color41   rgb(233,233,233)
color42   rgb(248,233,239)
color43   white
