# 14/07/2010 03:36 PM
# --------------------------------------------------------
nombre    ActualizarRetiroPorRespuestaBanco

# --------------------------------------------------------
conexion.nombre           CREADATOS 

# --------------------------------------------------------
operaciones:1.nombre             actualizarRetiroPorRespuestaBanco
operaciones:1.consulta.sql       update $RETIROS$ set $RETIROS.ESTADO DE RESPUESTA BANCO$ = #estado_respuesta#, $RETIROS.ESTADO$=$S('F')$, $RETIROS.TIPO ACTUALIZACION$ = #tipo_actualizacion#, $RETIROS.ACTUALIZACION$ = $T(SYSDATE)$, $RETIROS.RECHAZADO$ = #rechazado# where id = #codigo_referencia#

operaciones:1.parametros:1.nombre       codigo_referencia 
operaciones:1.parametros:1.tipo         string 

operaciones:1.parametros:2.nombre       estado_respuesta 
operaciones:1.parametros:2.tipo         string
operaciones:1.parametros:2.encriptado 	S

operaciones:1.parametros:3.nombre       tipo_actualizacion 
operaciones:1.parametros:3.tipo         string
operaciones:1.parametros:3.encriptado 	S

operaciones:1.parametros:4.nombre       rechazado 
operaciones:1.parametros:4.tipo         boolean
operaciones:1.parametros:4.encriptado 	S
 
operaciones:1.resultados:0.nombre       salida
operaciones:1.resultados:0.tipo         int
