# 14/07/2010 03:36 PM
# --------------------------------------------------------
nombre     BANCOS

# --------------------------------------------------------
conexion.nombre           CREADATOS 

# --------------------------------------------------------
operaciones:1.nombre             bancos
operaciones:1.consulta.sql       select c1220 codigo, c1221 nombre from t1180 where idcarga=0

operaciones:1.resultados:1.nombre        codigo
operaciones:1.resultados:1.tipo          string

operaciones:1.resultados:2.nombre        nombre
operaciones:1.resultados:2.tipo          string
