# 5/05/2009 06:07 PM
# --------------------------------------------------------
nombre     ejecucion

# --------------------------------------------------------
conexion.nombre           DATASUITE

# --------------------------------------------------------
operaciones:1.nombre            finalizar
operaciones:1.consulta.sql      UPDATE dst_ejecucion SET estado=#estado#, fecha_final=now() WHERE id_ejecucion = #id_ejecucion#

operaciones:1.parametros:0.nombre       estado
operaciones:1.parametros:0.tipo         string

operaciones:1.parametros:1.nombre       id_ejecucion
operaciones:1.parametros:1.tipo         int


operaciones:1.resultados:0.nombre       salida
operaciones:1.resultados:0.tipo         int

