# 5/05/2009 06:07 PM
# --------------------------------------------------------
nombre     guardarLog

# --------------------------------------------------------
conexion.nombre           CREADATOS

# --------------------------------------------------------
operaciones:1.nombre             guardar
operaciones:1.consulta.sql      insert into LOG (id_log, id_carga, id_ejecucion, cod_error, descripcion, fecha, ref1, ref2, ref3) values ( nextvalue('CDS_LOG'), #id_carga#, #id_ejecucion#, #codigo#, #descripcion#, now(), #ref1#, #ref2#, #ref3#)

operaciones:1.parametros:0.nombre       id_carga
operaciones:1.parametros:0.tipo         int

operaciones:1.parametros:1.nombre       id_ejecucion
operaciones:1.parametros:1.tipo         int

operaciones:1.parametros:2.nombre       codigo
operaciones:1.parametros:2.tipo         int

operaciones:1.parametros:3.nombre       descripcion
operaciones:1.parametros:3.tipo         string

operaciones:1.parametros:4.nombre       ref1
operaciones:1.parametros:4.tipo         string

operaciones:1.parametros:5.nombre       ref2
operaciones:1.parametros:5.tipo         string

operaciones:1.parametros:6.nombre       ref3
operaciones:1.parametros:6.tipo         string

operaciones:1.resultados:0.nombre       salida
operaciones:1.resultados:0.tipo         int

