################
# --------------------------------------------------------
titulo     	titulo

nombre     	Administrador de registro

id			administracioncarga_3b

consulta	select id_neg, cod_negocio, (cod_negocio||'-'||nombre) nombre, pendientes_aprobar, pendientes_ejecutar, (pendientes_aprobar + pendientes_ejecutar) pendientes_total from ( select distinct  n.id_negocio id_neg, n.cod_negocio cod_negocio, n.nombre nombre, (select count(DISTINCT cs.id_carga) from dst_carga cs where cs.id_negocio = n.id_negocio  and cs.estado in ('S')) pendientes_aprobar, (select count(DISTINCT cs.id_carga) from dst_carga cs where cs.id_negocio = n.id_negocio  and cs.estado in ('C')) pendientes_ejecutar from dst_negocio n, dst_administrador_negocio an where n.id_negocio = an.id_negocio and n.activo = 'S' and an.id_administrador = #id_administrador#)  order by pendientes_total desc, nombre

 
nombre_conexion           DATASUITE

# --------------------------------------------------------

resultados:1.titulo			Identificador
resultados:1.nombre			id_neg
resultados:1.tipo			integer
resultados:1.orden			1
resultados:1.encriptado		N
resultados:1.oculto			S

resultados:2.titulo			Codigo Negocio
resultados:2.nombre			cod_negocio
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		N
resultados:2.oculto			S

resultados:3.titulo			Negocio
resultados:3.nombre			nombre
resultados:3.tipo			string
resultados:3.orden			3
resultados:3.encriptado		N

resultados:4.titulo			Sin Aprobar
resultados:4.nombre			pendientes_aprobar
resultados:4.tipo			string
resultados:4.orden			4
resultados:4.encriptado		N

resultados:5.titulo			Sin Ejecutar
resultados:5.nombre			pendientes_ejecutar
resultados:5.tipo			string
resultados:5.orden			5
resultados:5.encriptado		N

resultados:6.titulo			Total
resultados:6.nombre			pendientes_total
resultados:6.tipo			string
resultados:6.orden			6
resultados:6.encriptado		N

# --------------------------------------------------------

accionfila.subreporte			administracioncarga_3b_1

accionfila.parametros:0.nombre	id_neg
accionfila.parametros:0.valor	#id_neg#
accionfila.parametros:0.tipo	string

#---------------------------------------------------------

navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do


