package test;

import java.util.List;
import java.util.Map;

import co.htsoft.commons.lang.P;

import com.ibatis.dao.client.DaoManager;
import com.osmosyscol.datasuite.logica.servicios.DatosEstructuraServicio;
import com.osmosyscol.datasuite.persistencia.dao.SQLDao;
import com.osmosyscol.datasuite.reportedim.servicio.RDServicio;
import com.osmosyscol.datasuite.test.TestUtils;
import com.osmosyscol.persistencia.dao.ibatis.core.DaoConfig;

public class QueryReporteNearTest {
	public static void main(String[] args) {
		TestUtils.startUp();
		String query = "SELECT $TIPO SOLICITUD.TIPO SOLICITUD$ TIPO_SOLICITUD, DB.$PERSONA.IDENTIFICACION$ NIT, T.NOMBRE_CLIENTE NOMBRE, 'TIPO_PERSONA' TIPO_PERSONA,"
						+ " 'TIPO_PERSONA_NATURAL' TIPO_PERSONA_NATURAL, $SOCIEDAD.ACTIVIDAD ECONOMICA$ CODIGO_CIIU, CIUDAD.$MUNICIPIOS DANE.NOMBRE CIUDAD$ CIUDAD_DOMICILIO, "
						+ "DEPARTAMENTO.$DEPARTAMENTOS DANE.NOMBRE DEPARTAMENTO$ DEPARTAMENTO_DOMICILIO, T.ID_CARGA RADICADO, T.FECHA_LIBERACION FECHA_RADICADO, $INFORMACION FINANCIERA.VALOR ACTIVOS$ ACTIVO_MILES, "
						+ "$INFORMACION FINANCIERA.VALOR PASIVOS$ PASIVO_MILES, $INFORMACION FINANCIERA.VALOR PATRIMONIO$ PATRIMONIO_MILES, T.FECHA_LIBERACION FECHA_CORTE_FINANCIERA, "
						+ "$SOCIEDAD.TRABAJADORES HOMBRES$ TRABAJADORES_HOMBRES, $SOCIEDAD.TRABAJADORES MUJERES$ TRABAJADORES_MUJERES, 'CAUSAL_INSOLVENCIA' CAUSAL_INSOLVENCIA, "
						+ "'CAUSAL_INSOLVENCIA_OTRA' CAUSAL_INSOLVENCIA_OTRA, 'REGIONAL' REGIONAL, $SOCIEDAD.TAMANO EMPRESA$ TAM_LEY_905, $SOCIEDAD.CATAEGORIA$ CATEGORIA_SUPERSOC, "
						+ "'TIPO_SOLICITUD_REORGANIZACION' TIPO_SOLICITUD_REORGANIZACION, $INFORMACION FINANCIERA.TOTAL INGRESOS ORDINARIOS$ INGRESOS_ACTIV_ORDINARIAS, $TIPO SOLICITUD.NORMA APLICABLE$ NORMA_ACOGE, "
						+ "$INFORMACION FINANCIERA.TOTAL OTROS INGRESOS$ OTROS_INGRESOS_MILES, $TIPO SOLICITUD.METODO$ PARTICIPACION_PERDIDAS, $SOCIEDAD.MACROSECTOR$ MACROSECTOR, $SOCIEDAD.CATAEGORIA$ CATEGORIA, "
						+ "'REGIONALES' REGIONALES, $TIPO SOLICITUD.GRUPO NIIF$ GRUPO_NIIF, $SOCIEDAD.TAMANO EMPRESA$ TAMANIO FROM $SOLICITUD NEAR SOCIEDAD$ SNC "
						+ " LEFT JOIN $SOCIEDAD$ S ON SNC.$SOLICITUD NEAR SOCIEDAD.DEUDOR$ = S.ID LEFT JOIN $TIPO SOLICITUD$ TS ON SNC.$SOLICITUD NEAR SOCIEDAD.TIPO SOLICITUD$ = TS.ID "
						+ " LEFT JOIN $INFORMACION FINANCIERA$ I ON SNC.$SOLICITUD NEAR SOCIEDAD.INFORMACION FINANCIERA$ = I.ID LEFT JOIN TS01 T ON T.ID_CARGA = SNC.IDCARGA "
						+ " LEFT JOIN $DEPARTAMENTOS DANE$ DEPARTAMENTO ON DEPARTAMENTO.ID = $SOCIEDAD.DEPARTAMENTO DANE$ LEFT JOIN $MUNICIPIOS DANE$ CIUDAD ON CIUDAD.ID = $SOCIEDAD.MUNICIPIO DANE$ "
						+ "LEFT JOIN $PERSONA$ DB on S.$SOCIEDAD.DATOS BASICOS$ = DB.ID WHERE T.FECHA_LIBERACION >= to_date('" + "31-12-2019" + " ','DD-MM-YYYY')";
		String sql = RDServicio.reemplazarNombres(query);
		DaoManager daoManager = DaoConfig.getDaoManager(2);
		SQLDao sqlDao = (SQLDao) daoManager.getDao(SQLDao.class);
		List<Map<String, Object>> lista = sqlDao.selectSQL(sql);
		lista = DatosEstructuraServicio.getInstance().desencriptarLista(lista);
		P.println(lista);
		System.exit(0);
	}
}
