################
# --------------------------------------------------------
nombre     	gruposgiro_carga

id			gruposgiro_carga

consulta	SELECT COUNT(1) - ( select count(*) total from $RETIROS$, $GRUPO GIRO$ WHERE $RETIROS$.IDCARGA = #id_carga# and $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM and nvl2($GRUPO GIRO.ARCHIVO$,2,null)=2 ) TOTAL, $RETIROS.PRODUCTO$ PRODUCTO, CP.*  FROM $RETIROS$  LEFT JOIN (  SELECT distinct COALESCE(C1.ID, C2.ID) CUENTA_ID_DEFECTO,  COALESCE(C1.$CUENTA - BANCO.CUENTA BANCARIA$, C2.$CUENTA - BANCO.CUENTA BANCARIA$) CUENTA_DEFECTO,  $BANCO.NOMBRE$ BANCO, $RETIROS$.IDCARGA  FROM $RETIROS$  INNER JOIN $BENEFICIARIO$ ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$  LEFT JOIN (SELECT A.* FROM $CUENTA - BANCO$ A, $BANCO$ B  WHERE $CUENTA - BANCO.BANCO$ = B.ID AND NVl($BANCO.ESTADO$,$S(A)$) <> $S(I)$) C1 ON C1.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$  AND $BENEFICIARIO.BANCO$ = C1.$CUENTA - BANCO.BANCO$  LEFT JOIN (SELECT A.* FROM $CUENTA - BANCO$ A, $BANCO$ B  WHERE $CUENTA - BANCO.BANCO$ = B.ID AND NVl($BANCO.ESTADO$,$S(A)$) <> $S(I)$) C2 ON C2.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$ AND C1.ID IS NULL AND C2.$CUENTA - BANCO.POR DEFECTO$ = $B(true)$  LEFT JOIN $BANCO$ B1 ON B1.ID = C1.$CUENTA - BANCO.BANCO$  OR B1.ID = C2.$CUENTA - BANCO.BANCO$  WHERE  not exists( select 1 from $GRUPO GIRO$ where $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM ) and  ( select count(1) from (select count(1) from $RETIROS$ INNER JOIN $BENEFICIARIO$  ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$  and $RETIROS$.IDCARGA = #id_carga# GROUP BY $BENEFICIARIO.BANCO$ ) bancos_diferentes ) = 1 and $RETIROS$.IDCARGA = #id_carga# ) CP ON CP.IDCARGA = $RETIROS$.IDCARGA WHERE $RETIROS$.IDCARGA = #id_carga# GROUP BY $RETIROS.PRODUCTO$, CP.CUENTA_ID_DEFECTO, CP.CUENTA_DEFECTO, CP.BANCO, CP.IDCARGA 
#consulta	SELECT COUNT(1) - ( select count(*) total from $RETIROS$, $GRUPO GIRO$ WHERE $RETIROS$.IDCARGA = #id_carga# and $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM and nvl2($GRUPO GIRO.ARCHIVO$,2,null)=2 ) TOTAL, $RETIROS.PRODUCTO$ PRODUCTO, CP.*  FROM $RETIROS$  LEFT JOIN (  SELECT distinct COALESCE(C1.ID, C2.ID) CUENTA_ID_DEFECTO,  COALESCE(C1.$CUENTA - BANCO.CUENTA BANCARIA$, C2.$CUENTA - BANCO.CUENTA BANCARIA$) CUENTA_DEFECTO,  $BANCO.NOMBRE$ BANCO, $RETIROS$.IDCARGA  FROM $RETIROS$  INNER JOIN $BENEFICIARIO$ ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$  LEFT JOIN $CUENTA - BANCO$ C1 ON C1.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$  AND $BENEFICIARIO.BANCO$ = C1.$CUENTA - BANCO.BANCO$  LEFT JOIN $CUENTA - BANCO$ C2 ON C2.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$ AND C1.ID IS NULL AND C2.$CUENTA - BANCO.POR DEFECTO$ = $B(true)$  LEFT JOIN $BANCO$ B1 ON B1.ID = C1.$CUENTA - BANCO.BANCO$  OR B1.ID = C2.$CUENTA - BANCO.BANCO$  ,( select count(1) from $RETIROS$ INNER JOIN $BENEFICIARIO$  ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$  and $RETIROS$.IDCARGA = #id_carga# GROUP BY $BENEFICIARIO.BANCO$ ) bancos_diferentes WHERE  ( select count(1) from $GRUPO GIRO$ where $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM )  = 0 and total_bancos  = 1 and $RETIROS$.IDCARGA = #id_carga# ) CP ON CP.IDCARGA = $RETIROS$.IDCARGA WHERE $RETIROS$.IDCARGA = #id_carga# GROUP BY $RETIROS.PRODUCTO$, CP.CUENTA_ID_DEFECTO, CP.CUENTA_DEFECTO, CP.BANCO, CP.IDCARGA 

nombre_conexion           CREADATOS

# --------------------------------------------------------
parametros:0.nombre 		id_carga
parametros:0.tipo 			integer

resultados:1.nombre			producto
resultados:1.tipo			integer

resultados:2.nombre			total
resultados:2.tipo			integer

resultados:3.nombre			cuenta_id_defecto
resultados:3.tipo			integer

resultados:4.nombre			cuenta_defecto
resultados:4.tipo			string
resultados:4.encriptado		S


resultados:5.nombre			banco
resultados:5.tipo			string
resultados:5.encriptado		S

