################
# --------------------------------------------------------
nombre     	gruposgiro_gruposgiro

id			gruposgiro_gruposgiro

consulta 		SELECT $GRUPO DE GIRO$.ID ID_REGISTRO, $GRUPO DE GIRO.CODIGO$ CODIGO, $GRUPO DE GIRO.FECHA CREACION$ FECHA_CREACION, $GRUPO DE GIRO.PERSONA$ PERSONA FROM  $GRUPO DE GIRO$

nombre_conexion           CREADATOS

# --------------------------------------------------------

resultados:1.nombre			id_registro
resultados:1.tipo			integer
resultados:1.orden			1

resultados:2.nombre			codigo
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		S

resultados:3.nombre			fecha_creacion
resultados:3.tipo			date
resultados:3.orden			3
resultados:3.encriptado		S

resultados:5.nombre			persona
resultados:5.tipo			string
resultados:5.orden			5
resultados:5.encriptado		S


# --------------------------------------------------------
accionfila.subreporte				gruposgiro_registros

accionfila.parametros:0.nombre	id_grupo
accionfila.parametros:0.valor	#id_registro#

