################
# --------------------------------------------------------
nombre     	agrupar_registros_simple_contar

id			agrupar_registros_simple_contar

consulta	select count(1) as total from (SELECT  1 FROM $RETIROS$  LEFT JOIN $RETIRO - ESTADO$ on $RETIROS.ESTADO$ = $RETIRO - ESTADO$.ID   LEFT JOIN $GRUPO GIRO$ ON $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM   LEFT JOIN $CUENTA - BANCO$ C1 ON C1.ID = $GRUPO GIRO.CUENTA$   LEFT JOIN $BANCO$ B1 ON B1.ID = C1.$CUENTA - BANCO.BANCO$   LEFT JOIN $BENEFICIARIO$ ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$   LEFT JOIN $BANCO$ B2 ON B2.ID = $BENEFICIARIO.BANCO$  INNER JOIN TS01 ON $RETIROS$.IDCARGA = TS01.ID_CARGA AND TS01.ESTADO = 'C' WHERE B1.ID = #id_banco# AND $GRUPO GIRO.ARCHIVO$ is null AND $RETIROS.TIPO DE RETIRO$ = $S(ACH)$) t   		

nombre_conexion           CREADATOS

# --------------------------------------------------------

parametros:0.nombre 		id_banco
parametros:0.tipo 			integer

resultados:1.nombre			total
resultados:1.tipo			integer
