###############
# --------------------------------------------------------
nombre     	agrupar_registros_simple

id			agrupar_registros_simple

consulta	SELECT  $GRUPO GIRO$.ID ID_GRUPO_GIRO, C1.ID CUENTA_PAGO_ID, $GRUPO GIRO.FECHA PAGO$ FECHA_PAGO FROM $RETIROS$ inner JOIN $GRUPO GIRO$ ON $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM   inner JOIN $CUENTA - BANCO$ C1 ON C1.ID = $GRUPO GIRO.CUENTA$   inner JOIN $BANCO$ B1 ON B1.ID = C1.$CUENTA - BANCO.BANCO$   inner JOIN $BENEFICIARIO$ ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$   inner JOIN $BANCO$ B2 ON B2.ID = $BENEFICIARIO.BANCO$  INNER JOIN TS01 ON $RETIROS$.IDCARGA = TS01.ID_CARGA AND TS01.ESTADO = 'C' WHERE ((#id_banco# is not null and B1.ID = #id_banco# ) or (#id_registro# is not null and $GRUPO GIRO$.ID = #id_registro#) ) AND nvl2($GRUPO GIRO.ARCHIVO$,null,1)=1 AND $RETIROS.TIPO DE RETIRO$ = $S(ACH)$   		

nombre_conexion           CREADATOS

# --------------------------------------------------------

parametros:0.nombre 		id_banco
parametros:0.tipo 			integer

parametros:1.nombre 		id_registro
parametros:1.tipo 			integer

resultados:12.nombre		id_grupo_giro
resultados:12.tipo			integer

resultados:13.nombre		cuenta_pago_id
resultados:13.tipo			integer

###Solo se necesitan comparar las fechas, no se desencripta
resultados:9.nombre			fecha_pago
resultados:9.tipo			string
