################
# --------------------------------------------------------
nombre     	gruposgiro_registros_simple

id			gruposgiro_registros_simple

consulta	select * from ( select p_.*, rownum rn from (    SELECT $RETIROS$.ID ID_REGISTRO, C1.ID ID_CUENTA, COALESCE(C2.ID, C3.ID) CUENTA_ID_DEFECTO  FROM $RETIRO - ESTADO$, $RETIROS$ INNER JOIN $BENEFICIARIO$ ON $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$ LEFT JOIN $GRUPO GIRO$ ON $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM LEFT JOIN $ARCHIVO$ ON $ARCHIVO$.ID = $GRUPO GIRO.ARCHIVO$ LEFT JOIN $BANCO$ B2 ON B2.ID = $BENEFICIARIO.BANCO$   LEFT JOIN $CUENTA - BANCO$ C1 ON C1.ID = $GRUPO GIRO.CUENTA$ LEFT JOIN (SELECT A.* FROM $CUENTA - BANCO$ A, $BANCO$ B  WHERE $CUENTA - BANCO.BANCO$ = B.ID AND NVl($BANCO.ESTADO$,$S(A)$) <> $S(I)$) C2  ON C2.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$  AND $BENEFICIARIO.BANCO$ = C2.$CUENTA - BANCO.BANCO$ AND C1.ID IS NULL  LEFT JOIN (SELECT A.* FROM $CUENTA - BANCO$ A, $BANCO$ B  WHERE $CUENTA - BANCO.BANCO$ = B.ID AND NVl($BANCO.ESTADO$,$S(A)$) <> $S(I)$) C3  ON C3.$CUENTA - BANCO.PRODUCTO$ = $RETIROS.PRODUCTO$  AND C1.ID IS NULL AND C2.ID IS NULL AND C3.$CUENTA - BANCO.POR DEFECTO$ = $B(true)$ LEFT JOIN $BANCO$ B1 ON B1.ID = C1.$CUENTA - BANCO.BANCO$ OR B1.ID = C2.$CUENTA - BANCO.BANCO$ OR B1.ID = C3.$CUENTA - BANCO.BANCO$ WHERE $RETIROS$.IDCARGA = #id_carga#   AND ( $RETIRO - ESTADO$.ID = $RETIROS.ESTADO$ OR ( $RETIRO - ESTADO$.ID = #estado_nuevo# AND $RETIROS.ESTADO$ IS NULL )  ) and nvl2($GRUPO GIRO.ARCHIVO$,null,1)=1 order by $RETIROS$.ID                  ) p_ ) q_ where q_.rn > #inicio# and q_.rn <= (#registros# + #inicio#) order by q_.rn   
nombre_conexion           CREADATOS

# --------------------------------------------------------
parametros:0.nombre 		id_carga
parametros:0.tipo 			integer

parametros:1.nombre 		estado_nuevo
parametros:1.tipo 			string
parametros:1.encriptado		S

parametros:2.nombre 		inicio
parametros:2.tipo 			integer

parametros:3.nombre 		registros
parametros:3.tipo 			integer

resultados:5.nombre			id_registro
resultados:5.tipo			integer
resultados:5.orden			5

resultados:14.nombre		cuenta_id_defecto
resultados:14.tipo			integer

resultados:16.nombre		id_cuenta
resultados:16.tipo			integer
