################
# --------------------------------------------------------
nombre     	Productos

id			saldo_productos

consulta        SELECT * FROM ( SELECT id id_interno, $PRODUCTO.ID$ ID_PRODUCTO, $PRODUCTO.NOMBRE$ NOMBRE, $PRODUCTO.LINEA DE PRODUCTO$ LINEA_PRODUCTO, ( select count(1) from $ENCARGO$ WHERE $ENCARGO.PRODUCTO$ = $PRODUCTO$.id AND $ENCARGO.ID CLIENTE$ = $I(#id_usuario#)$ AND $PRODUCTO.ACTIVO$ = $B(true)$ AND $ENCARGO.ACTIVO$ = $B(true)$  ) ENCARGOS FROM $PRODUCTO$ WHERE $PRODUCTO.LINEA DE PRODUCTO$ = #id_linea_producto#  ) T WHERE ENCARGOS > 0 

nombre_conexion           CREADATOS

# --------------------------------------------------------
parametros:1.nombre       	id_linea_producto 
parametros:1.tipo         	string

resultados:1.nombre        	nombre
resultados:1.titulo			Nombre
resultados:1.tipo          	string
resultados:1.orden         	1
resultados:1.encriptado   	S

resultados:3.nombre			ENCARGOS
resultados:3.titulo			Total Encargos
resultados:3.tipo			string
resultados:3.orden			2

resultados:2.nombre        	id_interno
resultados:2.tipo          	string
resultados:2.oculto         S

# --------------------------------------------------------
accionfila.subreporte			saldo_encargo

accionfila.parametros:0.nombre	id_producto
accionfila.parametros:0.valor	#id_interno#


# --------------------------------------------------------

navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do

