################
# --------------------------------------------------------
nombre     	Lineas de Producto

id			saldo_lineas_de_producto_total

consulta 		SELECT $PRODUCTO$.ID ID_INTERNO, $ENCARGO.SALDO$ total_linea_producto FROM $LINEA DE PRODUCTO$, $ENCARGO$, $PRODUCTO$ WHERE $PRODUCTO.LINEA DE PRODUCTO$ = $LINEA DE PRODUCTO$.ID AND  $ENCARGO.PRODUCTO$ = $PRODUCTO$.ID ORDER BY $PRODUCTO$.ID


nombre_conexion           CREADATOS

# --------------------------------------------------------

resultados:1.nombre			ID_INTERNO
resultados:1.titulo			Nombre
resultados:1.tipo			string
resultados:1.orden			1


resultados:2.nombre			total_linea_producto
resultados:2.titulo			Total SALDO
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		S

# --------------------------------------------------------

