package com.osmosyscol.datasuite.logica.dto;

public class FormatoOperacion {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    private Long id_formato_operacion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    private Long id_formato;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_CAMPO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    private Long id_campo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    private Long id_operacion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_LISTADINAMICA
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    private Long id_listadinamica;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO_OPERACION
     *
     * @return the value of DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public Long getId_formato_operacion() {
        return id_formato_operacion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO_OPERACION
     *
     * @param id_formato_operacion the value for DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void setId_formato_operacion(Long id_formato_operacion) {
        this.id_formato_operacion = id_formato_operacion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO
     *
     * @return the value of DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public Long getId_formato() {
        return id_formato;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO
     *
     * @param id_formato the value for DATASUITE_US.DST_FORMATO_OPERACION.ID_FORMATO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void setId_formato(Long id_formato) {
        this.id_formato = id_formato;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_CAMPO
     *
     * @return the value of DATASUITE_US.DST_FORMATO_OPERACION.ID_CAMPO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public Long getId_campo() {
        return id_campo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_CAMPO
     *
     * @param id_campo the value for DATASUITE_US.DST_FORMATO_OPERACION.ID_CAMPO
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void setId_campo(Long id_campo) {
        this.id_campo = id_campo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_OPERACION
     *
     * @return the value of DATASUITE_US.DST_FORMATO_OPERACION.ID_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public Long getId_operacion() {
        return id_operacion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_OPERACION
     *
     * @param id_operacion the value for DATASUITE_US.DST_FORMATO_OPERACION.ID_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void setId_operacion(Long id_operacion) {
        this.id_operacion = id_operacion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_LISTADINAMICA
     *
     * @return the value of DATASUITE_US.DST_FORMATO_OPERACION.ID_LISTADINAMICA
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public Long getId_listadinamica() {
        return id_listadinamica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column DATASUITE_US.DST_FORMATO_OPERACION.ID_LISTADINAMICA
     *
     * @param id_listadinamica the value for DATASUITE_US.DST_FORMATO_OPERACION.ID_LISTADINAMICA
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void setId_listadinamica(Long id_listadinamica) {
        this.id_listadinamica = id_listadinamica;
    }
}