################
# --------------------------------------------------------
nombre     	agrupar_bancocuenta

id			agrupar_bancocuenta

consulta 		SELECT  $GRUPO GIRO.CUENTA$ ID_CUENTA, $CUENTA - BANCO.CODIGO$ CODIGO_CUENTA, $CUENTA - BANCO.CUENTA BANCARIA$ NUMERO_CUENTA, $BANCO.NOMBRE$ BANCO FROM $GRUPO GIRO$, $CUENTA - BANCO$, $BANCO$ WHERE $GRUPO GIRO.CUENTA$ = $CUENTA - BANCO$.ID AND $CUENTA - BANCO.BANCO$ = $BANCO$.ID AND nvl2($GRUPO GIRO.ARCHIVO$,null,1)=1 GROUP BY $GRUPO GIRO.CUENTA$, $CUENTA - BANCO.CODIGO$, $CUENTA - BANCO.CUENTA BANCARIA$, $BANCO.NOMBRE$       

nombre_conexion           CREADATOS

# --------------------------------------------------------

resultados:1.nombre			id_cuenta
resultados:1.tipo			integer
resultados:1.orden			1

resultados:2.nombre			codigo_cuenta
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		S

resultados:3.nombre			numero_cuenta
resultados:3.tipo			string
resultados:3.orden			3
resultados:3.encriptado		S

resultados:5.nombre			banco
resultados:5.tipo			string
resultados:5.orden			5
resultados:5.encriptado		S


