################
# --------------------------------------------------------
nombre     	agrupar_banco

id			agrupar_banco

consulta	SELECT   $BANCO.NOMBRE$ BANCO , $BANCO$.ID ID_BANCO  FROM $GRUPO GIRO$  INNER JOIN $CUENTA - BANCO$ ON $GRUPO GIRO.CUENTA$ = $CUENTA - BANCO$.ID   INNER JOIN $BANCO$ ON  $BANCO$.ID = nvl($CUENTA - BANCO.BANCO$, -1)    INNER JOIN $RETIROS$ ON $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM  and  $RETIROS.TIPO DE RETIRO$ = $S(ACH)$ WHERE nvl2($GRUPO GIRO.ARCHIVO$,null,1)=1   GROUP BY $BANCO.NOMBRE$, $BANCO$.ID ORDER BY $BANCO.NOMBRE$	

nombre_conexion           CREADATOS

# --------------------------------------------------------

resultados:1.nombre			id_banco
resultados:1.tipo			integer
resultados:1.orden			1

resultados:2.nombre			banco
resultados:2.tipo			string
resultados:2.orden			5
resultados:2.encriptado		S


