################
# --------------------------------------------------------
nombre     	agrupar_registros

id			agrupar_registros
 
consulta	SELECT * FROM     (         SELECT P_.*,             ROWNUM RN         FROM             (                 SELECT $RETIROS$.ID ID_REGISTRO,                     (SELECT $BENEFICIARIO.NUMERO DE DOCUMENTO$ FROM $BENEFICIARIO$ WHERE $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$)IDENTIFICACION,                     $RETIROS.VALOR$ VALOR,                     B2.$BANCO.NOMBRE$ BANCO,                     (SELECT $BENEFICIARIO.NUMERO DE CUENTA$ FROM $BENEFICIARIO$ WHERE $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$) CUENTA ,                     B1.$BANCO.NOMBRE$ BANCO_PAGO,                     $RETIRO - ESTADO$.NOMBRE ESTADO,                     C1.$CUENTA - BANCO.CUENTA BANCARIA$ CUENTA_PAGO,                     C1.ID CUENTA_PAGO_ID,                     $GRUPO GIRO.FECHA PAGO$ FECHA_PAGO,                     $GRUPO GIRO$.ID ID_GRUPO_GIRO                 FROM $RETIROS$                 LEFT JOIN $RETIRO - ESTADO$                 ON  $RETIROS.ESTADO$ = $RETIRO - ESTADO$.ID                 INNER JOIN $GRUPO GIRO$                 ON  $RETIROS$.ID = $GRUPO GIRO.CODIGO REGISTRO$_NUM                 INNER JOIN $CUENTA - BANCO$ C1                 ON  C1.ID = $GRUPO GIRO.CUENTA$                 INNER JOIN $BANCO$ B1                 ON  B1.ID = NVL(C1.$CUENTA - BANCO.BANCO$, -1)                 INNER JOIN $BENEFICIARIO$                 ON  $BENEFICIARIO$.ID = $RETIROS.BENEFICIARIO$                 LEFT JOIN $BANCO$ B2                 ON  B2.ID = $BENEFICIARIO.BANCO$                 INNER JOIN TS01                 ON  $RETIROS$.IDCARGA        = TS01.ID_CARGA                 AND TS01.ESTADO              = 'C'                 WHERE B1.ID                  = #id_banco#                 AND nvl2($GRUPO GIRO.ARCHIVO$,2,1) = 1 AND $RETIROS.TIPO DE RETIRO$ = $S(ACH)$                 ORDER BY $GRUPO GIRO.FECHA PAGO$,                     C1.ID             )             P_     )     Q_ WHERE Q_.RN > #inicio# AND Q_.RN  <= (#registros# + #inicio#) ORDER BY Q_.RN  		

nombre_conexion           CREADATOS

# --------------------------------------------------------

parametros:0.nombre 		id_banco
parametros:0.tipo 			integer


parametros:2.nombre 		inicio
parametros:2.tipo 			integer

parametros:3.nombre 		registros
parametros:3.tipo 			integer

resultados:1.nombre			identificacion
resultados:1.encriptado		S
resultados:1.tipo			string
resultados:1.orden			1

resultados:2.nombre			valor
resultados:2.tipo			money
resultados:2.orden			2
resultados:2.encriptado		S

resultados:3.nombre			banco
resultados:3.tipo			string
resultados:3.orden			3
resultados:3.encriptado		S

resultados:4.nombre			cuenta
resultados:4.tipo			string
resultados:4.orden			4
resultados:4.encriptado		S

resultados:5.nombre			id_registro
resultados:5.tipo			integer
resultados:5.orden			5

resultados:7.nombre			estado
resultados:7.tipo			string
resultados:7.encriptado		S

resultados:8.nombre			cuenta_pago
resultados:8.tipo			string
resultados:8.encriptado		S

resultados:9.nombre			fecha_pago
resultados:9.tipo			date
resultados:9.encriptado		S

resultados:12.nombre		id_grupo_giro
resultados:12.tipo			integer

resultados:13.nombre		cuenta_pago_id
resultados:13.tipo			integer

