# --------------------------------------------------------
nombre     	Archivos de Salida a Banco

id			archivos_salida

consulta	select $ARCHIVO$.ID id_interno, $ARCHIVO.FECHA CREACION$ FECHA, $ARCHIVO.PERSONA$ PERSONA, $ARCHIVO.NOMBRE$ NOMBRE from $ARCHIVO$  ORDER BY FECHA DESC 		

nombre_conexion           CREADATOS

# --------------------------------------------------------

resultados:1.nombre			Fecha
resultados:1.titulo			FECHA
resultados:1.tipo			date
resultados:1.encriptado		S
resultados:1.orden			1

resultados:2.nombre			Nombre
resultados:2.titulo			NOMBRE
resultados:2.tipo			string
resultados:2.encriptado		S
resultados:2.orden			2

resultados:3.nombre			Persona
resultados:3.titulo			PERSONA
resultados:3.tipo			string
resultados:3.encriptado		S
resultados:3.orden			3


resultados:4.nombre			id_interno
resultados:4.tipo			string
resultados:4.oculto			S


# --------------------------------------------------------

accionfila.javascript			generarArchivo

accionfila.parametros:0.nombre	id_archivo
accionfila.parametros:0.valor	#id_interno#

accionfila.parametros:1.nombre	nombre_archivo
accionfila.parametros:1.valor	#Nombre#

# --------------------------------------------------------

navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do

