################
# --------------------------------------------------------

nombre		validacion_beneficiarios

id			validacion_beneficiarios

consulta	SELECT carga.nombre_cliente nombre_cliente, nonull(b.$BENEFICIARIO.PRIMER NOMBRE$) ||' '|| nonull(b.$BENEFICIARIO.SEGUNDO NOMBRE$)||' '|| nonull(b.$BENEFICIARIO.PRIMER APELLIDO$)||' '|| nonull(b.$BENEFICIARIO.SEGUNDO APELLIDO$) beneficiario, b.$BENEFICIARIO.NUMERO DE DOCUMENTO$ documento_beneficiario, b.$BENEFICIARIO.NUMERO DE CUENTA$ cuenta, bn.$BANCO.NOMBRE$ banco, tc.$TIPO DE CUENTA.DESCRIPCION$ tipocuenta, b.IDCARGA carga, carga.fecha_liberacion fecha_liberacion FROM  $BENEFICIARIO$ b INNER JOIN  $BANCO$ bn ON (b.$BENEFICIARIO.BANCO$ = bn.ID) INNER JOIN $TIPO DE CUENTA$ tc ON (b.$BENEFICIARIO.TIPO DE CUENTA$ =  tc.ID) INNER JOIN TS01 carga ON (b.IDCARGA = carga.id_carga) where carga.fecha_liberacion is not null and b.$BENEFICIARIO.VALIDACION PERSONA$= $B(true)$ and ( '#fecha_liberacion_desde#' = 'null' or  to_date(to_char(carga.fecha_liberacion,'dd/mm/yyyy'), 'dd/mm/yyyy') >= to_date('#fecha_liberacion_desde#', 'dd/mm/yyyy') ) and ( '#fecha_liberacion_hasta#' = 'null' or to_date(to_char(carga.fecha_liberacion,'dd/mm/yyyy'), 'dd/mm/yyyy') <= to_date('#fecha_liberacion_hasta#', 'dd/mm/yyyy') ) order by carga.fecha_liberacion desc 

nombre_conexion           CREADATOS

# --------------------------------------------------------

parametros:1.nombre			fecha_liberacion_desde
parametros:1.tipo			date
parametros:1.encriptado		N
parametros:1.orden			1
parametros:1.filtro			true
parametros:1.titulo			Fecha liberacion desde

parametros:2.nombre			fecha_liberacion_hasta
parametros:2.tipo			date
parametros:2.encriptado		N
parametros:2.orden			2
parametros:2.filtro			true
parametros:2.titulo			Fecha de liberacion hasta

resultados:1.titulo			Cliente
resultados:1.nombre			nombre_cliente
resultados:1.tipo			string
resultados:1.orden			1
resultados:1.encriptado		N

resultados:2.titulo			Beneficiario
resultados:2.nombre			beneficiario
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		S

resultados:3.titulo			Documento Beneficiario
resultados:3.nombre			documento_beneficiario
resultados:3.tipo			string
resultados:3.orden			3
resultados:3.encriptado		S

resultados:4.titulo			Cuenta Beneficiario
resultados:4.nombre			cuenta
resultados:4.tipo			string
resultados:4.orden			4
resultados:4.encriptado		S

resultados:5.titulo			Tipo de cuenta
resultados:5.nombre			tipocuenta
resultados:5.tipo			string
resultados:5.orden			5
resultados:5.encriptado		S

resultados:6.titulo			Banco
resultados:6.nombre			banco
resultados:6.tipo			string
resultados:6.orden			6
resultados:6.encriptado		S

resultados:7.titulo			Transaccion
resultados:7.nombre			carga
resultados:7.tipo			string
resultados:7.orden			7
resultados:7.encriptado		N

resultados:8.titulo			Fecha liberacion
resultados:8.nombre			fecha_liberacion
resultados:8.tipo			date
resultados:8.orden			8
resultados:8.encriptado		N

#-------------
navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do


