##############################################################

database.driver = oracle.jdbc.driver.OracleDriver

database.url = jdbc:oracle:thin:@oracle-db:1521:xe
database.user = OSMOAUTENTICADOR
database.password = OSMOAUTENTICADOR

##############################################################

database.name = OSMOAUTENTICADOR
database.id = 1
database.defecto = S

##############################################################

database.maxIdle                       = 3
database.maxWait                       = 80000
database.validationQuery               = select '1' from dual
database.testWhileIdle                 = true
database.testOnBorrow                  = true
database.timeBetweenEvictionRunsMillis = 300000

database.initialSize = 1
database.maxActive = 10

##############################################################
