# --------------------------------------------------------
nombre     informacionPersona

# --------------------------------------------------------
conexion.nombre           OSMOAUTENTICADOR

# --------------------------------------------------------
operaciones:1.nombre             informacionPersona
operaciones:1.consulta.sql       select p.primer_nombre, p.segundo_nombre, p.primer_apellido, p.segundo_apellido, p.correo, p.naturaleza, p.numero_documento,p.telefono from oat_persona p where p.numero_documento = #identificacion#


operaciones:1.parametros:1.nombre        identificacion
operaciones:1.parametros:1.tipo          string

operaciones:1.resultados:2.nombre        primer_nombre
operaciones:1.resultados:2.tipo          string

operaciones:1.resultados:3.nombre        segundo_nombre
operaciones:1.resultados:3.tipo          string

operaciones:1.resultados:4.nombre        primer_apellido
operaciones:1.resultados:4.tipo          string

operaciones:1.resultados:5.nombre        segundo_apellido
operaciones:1.resultados:5.tipo          string

operaciones:1.resultados:6.nombre        correo
operaciones:1.resultados:6.tipo          string

operaciones:1.resultados:7.nombre        naturaleza
operaciones:1.resultados:7.tipo          string

operaciones:1.resultados:8.nombre        numero_documento
operaciones:1.resultados:8.tipo          string

operaciones:1.resultados:9.nombre        telefono
operaciones:1.resultados:9.tipo          string

