# --------------------------------------------------------
nombre     UrlServicioApp

prefijo false

# --------------------------------------------------------
conexion.nombre           OSMOAUTENTICADOR

# --------------------------------------------------------
operaciones:1.nombre             listarUrlsServiciosApp
operaciones:1.consulta.sql       select distinct urls.url as url_servicio from OAT_ROL rol, OAT_APLICACION app, OAT_SERVICIO_ROL srol,  OAT_SERVICIO ser, OAT_URL_SERVICIO urls where rol.ID_APLICACION = app.ID_APLICACION and app.NOMBRE = 'BOTZIO' and rol.ID_ROL = srol.ID_ROL and srol.ID_SERVICIO = ser.ID_SERVICIO and ser.ID_SERVICIO = urls.ID_SERVICIO and ser.activo = 'S'

operaciones:1.parametros:1.nombre        aplicacion
operaciones:1.parametros:1.tipo          string

operaciones:1.resultados:1.nombre        url_servicio
operaciones:1.resultados:1.tipo          string
