# --------------------------------------------------------
nombre     listarDependenciasporURL

# --------------------------------------------------------
conexion.nombre           OSMOAUTENTICADOR

# --------------------------------------------------------

operaciones:4.nombre                     listarDependenciasporURL
operaciones:4.consulta.sql               SELECT distinct ur.id_dependencia, d.nombre FROM oat_dependencia d, oat_usuario u, oat_usuario_rol ur, oat_rol r, oat_servicio_rol sr, oat_servicio s, oat_url_servicio us WHERE d.id_dependencia = ur.id_dependencia and u.id_usuario = ur.id_usuario AND ur.id_rol = r.id_rol AND u.login = #login# and r.id_rol = sr.id_rol and sr.id_servicio = s.id_servicio and s.id_servicio = us.id_servicio and us.url = #url# and s.activo = 'S' and ur.estado = 'A' ORDER BY ur.id_dependencia 

operaciones:4.parametros:1.nombre        login
operaciones:4.parametros:1.tipo          string

operaciones:4.parametros:2.nombre        url
operaciones:4.parametros:2.tipo          string

operaciones:4.resultados:1.nombre        id_dependencia
operaciones:4.resultados:1.tipo          string

operaciones:4.resultados:2.nombre        nombre
operaciones:4.resultados:2.tipo          string
