# --------------------------------------------------------
nombre     UrlServicio

prefijo false

# --------------------------------------------------------
conexion.nombre           OSMOAUTENTICADOR

# --------------------------------------------------------
operaciones:1.nombre             obtenerUrlServicios
operaciones:1.consulta.sql       select rol.id_rol,rol.nombre as nombre_rol,ser.id_servicio,ser.nombre as nombre_servicio,urls.url as url_servicio from OAT_USUARIO usu,OAT_USUARIO_ROL urol, OAT_ROL rol, OAT_APLICACION app,OAT_SERVICIO_ROL srol,OAT_SERVICIO ser, OAT_URL_SERVICIO urls where upper(usu.LOGIN) = upper(#login#) and urol.ID_USUARIO = usu.ID_USUARIO and urol.ID_ROL = rol.ID_ROL and rol.ID_APLICACION = app.ID_APLICACION and app.NOMBRE = #aplicacion# and rol.ID_ROL = srol.ID_ROL and srol.ID_SERVICIO = ser.ID_SERVICIO and ser.ID_SERVICIO = urls.ID_SERVICIO and ser.activo='S' and urol.estado = 'A'

operaciones:1.parametros:1.nombre        login
operaciones:1.parametros:1.tipo          string

operaciones:1.parametros:2.nombre        aplicacion
operaciones:1.parametros:2.tipo          string

operaciones:1.resultados:1.nombre        id_rol
operaciones:1.resultados:1.tipo          int

operaciones:1.resultados:2.nombre        nombre_rol
operaciones:1.resultados:2.tipo          string

operaciones:1.resultados:3.nombre        id_servicio
operaciones:1.resultados:3.tipo          int

operaciones:1.resultados:4.nombre        nombre_servicio
operaciones:1.resultados:4.tipo          string

operaciones:1.resultados:5.nombre        url_servicio
operaciones:1.resultados:5.tipo          string
