# --------------------------------------------------------
nombre     roles_usuario

# --------------------------------------------------------
conexion.nombre           OSMOAUTENTICADOR

# --------------------------------------------------------
operaciones:1.nombre             adicionar_rol
operaciones:1.consulta.sql       insert into oat_usuario_rol (id_usuario, id_rol, estado, id_dependencia) values ( (select id_usuario from oat_usuario WHERE LOGIN = upper(#login#)) , #id_rol#, 'A', #id_dependencia#)

operaciones:1.parametros:1.nombre        login
operaciones:1.parametros:1.tipo          string

operaciones:1.parametros:2.nombre        id_rol
operaciones:1.parametros:2.tipo          int

operaciones:1.parametros:3.nombre        id_dependencia
operaciones:1.parametros:3.tipo          int

# ----

operaciones:1.resultados:1.nombre        registrados
operaciones:1.resultados:1.tipo          int

# --------------------------------------------------------

operaciones:2.nombre             eliminar_rol
operaciones:2.consulta.sql       delete oat_usuario_rol where id_usuario = ( select id_usuario from oat_usuario WHERE LOGIN = upper(#login#) ) and id_rol = #id_rol# and ((id_dependencia is null and #id_dependencia# is null ) or id_dependencia = #id_dependencia# ) 

operaciones:2.parametros:1.nombre        login
operaciones:2.parametros:1.tipo          string

operaciones:2.parametros:2.nombre        id_rol
operaciones:2.parametros:2.tipo          int

operaciones:2.parametros:3.nombre        id_dependencia
operaciones:2.parametros:3.tipo          int

# -----

operaciones:2.resultados:1.nombre        eliminados
operaciones:2.resultados:1.tipo          int

# --------------------------------------------------------
