package com.osmosyscol.datasuite.persistencia.dao.ibatis;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.ibatis.dao.client.DaoManager;
import com.osmosyscol.datasuite.logica.dto.FormatoOperacion;
import com.osmosyscol.datasuite.persistencia.dao.FormatoOperacionDao;
import com.osmosyscol.persistencia.dao.ibatis.core.BaseSqlMapDao;

public class FormatoOperacionDaoImp extends BaseSqlMapDao implements FormatoOperacionDao {


	public FormatoOperacionDaoImp(DaoManager daoManager) {
		super(daoManager);
	}
	
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public void insert(FormatoOperacion record) throws SQLException {
        insert("FormatoOperacion.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public int updateByPrimaryKey(FormatoOperacion record) throws SQLException {
        int rows = update("FormatoOperacion.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public FormatoOperacion selectByPrimaryKey(Long id_formato_operacion) throws SQLException {
        FormatoOperacion key = new FormatoOperacion();
        key.setId_formato_operacion(id_formato_operacion);
        FormatoOperacion record = (FormatoOperacion) queryForObject("FormatoOperacion.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table DATASUITE_US.DST_FORMATO_OPERACION
     *
     * @abatorgenerated Mon May 23 14:44:00 COT 2011
     */
    public int deleteByPrimaryKey(Long id_formato_operacion) throws SQLException {
        FormatoOperacion key = new FormatoOperacion();
        key.setId_formato_operacion(id_formato_operacion);
        int rows = delete("FormatoOperacion.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	public void eliminarPorFormato(long id_formato) {
		delete("FormatoOperacion.eliminarPorFormato", id_formato);		
	}

	public List<FormatoOperacion> obtenerOperacionesPorFormato(long id_formato) {
		return queryForList("FormatoOperacion.obtenerOperacionesPorFormato", id_formato);
	}

	public Long obtenerSiguienteId() {
		return (Long) queryForObject("FormatoOperacion.obtenerSiguienteId");
	}

	public List<Map<String, Object>> obtenerCamposTipoEstructura(Integer id_formato) {
		return queryForList("FormatoOperacion.obtenerCamposTipoEstructura" , id_formato);
	}

	public List<FormatoOperacion> obtenerOperacionesPorCarga(Integer id_carga) {
		return queryForList("FormatoOperacion.obtenerOperacionesPorCarga", id_carga);
	}

	public Integer obtenerEstructuraFormatoCarga(Integer id_carga) {
		return (Integer) queryForObject("FormatoOperacion.obtenerEstructuraFormatoCarga", id_carga);
	}
	
	

}