################
# --------------------------------------------------------
nombre     	Administrador de registro

id			administracioncarga_usuarios

consulta	SELECT #id_neg# id_neg, #id_proc# id_proceso, du.id_persona, du.id_usuario, dp.identificacion, (dp.nombre ||' ' || dp.apellido) nombre, (SELECT COUNT(*) FROM dst_carga dc WHERE dc.estado   = 'S' AND dc.id_usuario = du.id_usuario AND dc.id_proceso = #id_proc# AND dc.id_negocio = #id_neg# ) AS pendientes, (SELECT COUNT(*) FROM dst_carga dc WHERE dc.estado   = 'C' AND dc.id_usuario = du.id_usuario AND dc.id_proceso = #id_proc# AND dc.id_negocio = #id_neg# ) AS aprobadas, (SELECT COUNT(*) FROM dst_carga dc WHERE dc.estado  IN ('S','C') AND dc.id_usuario = du.id_usuario AND dc.id_proceso = #id_proc# AND dc.id_negocio = #id_neg# ) AS total FROM dst_usuario_negocio dun, dst_usuario du, dst_persona dp, dst_proceso p WHERE dun.id_usuario = du.id_usuario AND du.id_persona    = dp.id_persona AND dun.id_negocio   = #id_neg# and p.id_proceso = #id_proc#  and ( (p.id_usuario = du.id_usuario and p.id_negocio = #id_neg#) or (p.id_usuario is null and p.id_negocio is null) )  and du.activo = 'S' ORDER BY total DESC, dp.nombre	
 
nombre_conexion           DATASUITE

# --------------------------------------------------------

parametros:1.nombre       id_neg
parametros:1.tipo         integer

parametros:2.nombre       id_proc
parametros:2.tipo         integer

# --------------------------------------------------------

resultados:0.titulo			id_usuario
resultados:0.nombre			id_usuario
resultados:0.tipo			integer
resultados:0.orden			0
resultados:0.encriptado		N
resultados:0.oculto			S

resultados:1.titulo			Cedula
resultados:1.nombre			identificacion
resultados:1.tipo			string
resultados:1.orden			1
resultados:1.encriptado		N

resultados:2.titulo			Nombre
resultados:2.nombre			nombre
resultados:2.tipo			string
resultados:2.orden			2
resultados:2.encriptado		N

resultados:3.titulo			Sin Aprobar
resultados:3.nombre			pendientes
resultados:3.tipo			int
resultados:3.orden			3
resultados:3.encriptado		N

resultados:4.titulo			Sin Ejecutar
resultados:4.nombre			aprobadas
resultados:4.tipo			string
resultados:4.orden			4
resultados:4.encriptado		N

resultados:5.titulo			Total
resultados:5.nombre			total
resultados:5.tipo			string
resultados:5.orden			5
resultados:5.encriptado		N

resultados:6.titulo			id_neg
resultados:6.nombre			id_neg
resultados:6.tipo			integer
resultados:6.orden			6
resultados:6.encriptado		N
resultados:6.oculto			S

resultados:7.titulo			id_proceso
resultados:7.nombre			id_proceso
resultados:7.tipo			integer
resultados:7.orden			7
resultados:7.encriptado		N
resultados:7.oculto			S

resultados:8.titulo			id_persona
resultados:8.nombre			id_persona
resultados:8.tipo			integer
resultados:8.orden			8
resultados:8.encriptado		N
resultados:8.oculto			S

# --------------------------------------------------------

accionfila.destino		administracion_carga/3b.2.do

accionfila.parametros:0.nombre	id_proceso
accionfila.parametros:0.valor	#id_proceso#
accionfila.parametros:0.tipo	integer

accionfila.parametros:1.nombre	id_neg
accionfila.parametros:1.valor	#id_neg#
accionfila.parametros:1.tipo	integer

accionfila.parametros:2.nombre	id_usuario
accionfila.parametros:2.valor	#id_usuario#
accionfila.parametros:2.tipo	integer

#---------------------------------------------------------

navegacion:1.nombre					Inicio
navegacion:1.destino				inicio/0.do

navegacion:2.nombre					Volver
navegacion:2.destino				administracion_carga/3b.do

