######################################################################
# Configuracion Basica

system.debug	true

##############################################################

cifrado.algoritmo	SHA512,	MD5
